services:

  app:
    build: ..
    ports:
      - "4000:3000"
    depends_on:
      - mongo
      - redis
      - kafka
    environment:
      - MONGODB_URI=mongodb://mongo:27017/foodInt
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:9092
      - JWT_SECRET=b3dd6b865f8577f4cc8b72fcc63ca99f
      - IMAGEKIT_PUBLIC_KEY=public_qgwsUJ96V/OrdBqHyQTcF25kl4o=
      - IMAGEKIT_PRIVATE_KEY=private_texhg9gLDQCGMR1B9Pwy2+terV0=
      - IMAGEKIT_URL_ENDPOINT=https://ik.imagekit.io/t5mdehnzi

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data: